services:
  web:
    build: .
    ports:
      - "5050:5050"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    depends_on:
      - db
    environment:
      SECRET_KEY: "replaceinprod"
      DATABASE_URL: "postgresql://postgres:password@db/local_plans"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_plans
    expose:
    - "5433"
    ports:
      - "5433:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: "migrations"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db/local_plans"

volumes:
  pgdata:
